### ISSUE TITLE
Source information in Event tables

### ISSUE THREAD

**Issue by vijayambati1** [openedinc/callisto#24]
It would be nice if we can capture the source information into event tables. 

Caliper events contain this information in "edApp" section of the payload. We can create a "edApp_id" field in all 4 event tables and store this information for querying purpose. This will help query the events based on source. 

Any thoughts?

**Comment by larsburgess** [comment]
This sounds good, would it make sense to have something like (to put it in ActiveRecord terms):

```ruby
class Source < ApplicationRecord
  has_many :source_events

  has_many :assessment_events,
    through: :source_events,
    source: :eventable,
    source_type: 'AssessmentEvent'
  # ...
end

class SourceEvent < ApplicationRecord
  belongs_to :eventable, polymorphic: true
end

class AssessmentEvent < ApplicationRecord
  has_one :source_event, as: :eventable, dependent: :destroy
  has_one :source, through: :source_event
  # ...
end
```

This results in database tables like:

```ruby
  create_table "source_events", force: :cascade do |t|
    t.string "eventable_type"
    t.bigint "eventable_id"
    t.bigint "source_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["eventable_type", "eventable_id"], name: "index_source_events_on_eventable_type_and_eventable_id"
    t.index ["source_id"], name: "index_source_events_on_source_id"
  end


  create_table "sources", force: :cascade do |t|
    t.string "title"
    t.string "timestamps"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
```

Then to get the events of a certain type for a source it would be:

```irb
irb(main):001:0> source = Source.first

# Source Load (0.5ms)  SELECT  "sources".* FROM "sources" ORDER BY "sources"."id" ASC LIMIT $1  [["LIMIT", 1]]

=> #<Source id: 1, title: "myapp", timestamps: nil, created_at: "2018-02-08 00:45:05", updated_at: "2018-02-08 00:45:05">

irb(main):002:0> source.assessment_events.limit(2)

# AssessmentEvent Load (0.7ms)  SELECT  "assessment_events".* FROM "assessment_events" INNER JOIN "source_events" ON "assessment_events"."id" = "source_events"."eventable_id" WHERE "source_events"."source_id" = $1 AND "source_events"."eventable_type" = $2 LIMIT $3  [["source_id", 1], ["eventable_type", "AssessmentEvent"], ["LIMIT", 2]]

=> #<ActiveRecord::AssociationRelation [#<AssessmentEvent id: 70, actor_id: "https://staging.opened.com/user/1", action: "Submitted", object_id: "https://staging.opened.com/resources/1098453", generated_id: "https://staging.opened.com/assessment_run/2", generated_ended_at_time: nil, created_at: "2018-01-02 21:27:51", updated_at: "2018-01-02 21:27:51", group_id: nil, event_time: "2017-10-02 19:24:59">, #<AssessmentEvent id: 71, actor_id: "https://staging.opened.com/user/2", action: "Submitted", object_id: "https://staging.opened.com/resources/1098453", generated_id: "https://staging.opened.com/assessment_run/3", generated_ended_at_time: nil, created_at: "2018-01-02 21:27:51", updated_at: "2018-01-02 21:27:51", group_id: nil, event_time: "2017-10-02 19:24:59">]>
```

Using a polymorphic association here with a join table makes the code a little cleaner, we can of course add foreign keys between each of the event tables and the join table as well.

**Comment by vijayambati1** [comment]
From data ingestion point of view this might get bit complicated. As the data ingestion component need to know the assigned Source_Id from the database. If we can use "edApp_Id" kind of approach like we are using "actor_id" & "object_id" the data ingestion component can simply insert "edApp_Id" constructed from edApp section of the caliper payload. This way it doesn't need to know about the assigned Source_Id for a particular source.

Just trying to reduce the coupling between data ingestion components and callisto database.

**Comment by larsburgess** [comment]
I think it should be possible. We can have an `edapp_id` string column in the sources table and use that as the primary key for the relations. It might be something like:

```ruby
  create_table "sources", force: :cascade do |t|
    t.string "title"
    t.string "edapp_id"
    t.string "timestamps"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "source_events", force: :cascade do |t|
    t.string "eventable_type"
    t.bigint "eventable_id"
    t.string "edapp_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["eventable_type", "eventable_id"], name: "index_source_events_on_eventable_type_and_eventable_id"
    t.index ["source_id"], name: "index_source_events_on_source_id"
  end
```

```ruby
class SourceEvent < ApplicationRecord
  belongs_to :eventable, polymorphic: true, primary_key: 'edapp_id'
end

class AssessmentEvent < ApplicationRecord
  has_one :source_event, as: :eventable, dependent: :destroy 
  has_one :source, through: :source_event, foreign_key: 'edapp_id'
  # ...
end
```

You'd still need to create each record in the sources table, but it wouldn't matter what id they have. Alternatively, we could try setting the primary key field on sources table to the 'edapp_id' column. What do you think?

**Comment by vijayambati1** [comment]
Lars,

I believe for now if we can add just edApp_id field to all event tables that would be enough. If we need to have detailed information about the source we can add it later. As of today we don't get detailed information about source in caliper messages and we wont be feeding information into source table. as long as we can capture edApp_id field alone would be sufficient. In future we can add these tables if required. 

Trying not to pollute the schema with out the usecases for it. What do you say?

**Comment by larsburgess** [comment]
That's fine, we can always add the relation later if we take a tag approach to the field. I'd like to call it `edapp_id` to match the other column names in formatting.

**Comment by vijayambati1** [comment]
Perfect :)

**Comment by larsburgess** [comment]
Added via https://github.com/openedinc/callisto/commit/0b850f1fc0c7679c6cb394cd502427930577597d.
