### ISSUE TITLE
Why not capture both started and ended timestamps from "generated" section?

### ISSUE THREAD

**Issue by vijayambati1** [openedinc/callisto#25]
Whats the reasoning behind capturing only started or ended timestamps in "generated" section? why not both?

For example: In "assessment_events" table only "generated_ended_at_time" and in "assessment_item_events" table only "generated_started_at_time" fields are available.

**Comment by larsburgess** [comment]
@adamblum want to take this one? If I had to guess I think it's just loading what we needed at the time or it might just be missing. We can add it. Let me know.
